=== freedesktop-unofficial-mirror/apoc-template-packages/packages/dtd/policytemplate.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 ******************************************************************************* 
 * $RCSfile: policytemplate.dtd,v $
 *
 * Description: This file contains the APOC Template DTD.
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * Use of this product is subject to license terms.
 *
 *******************************************************************************
--> 

<!ELEMENT apt:template (resImport*, category)>
<!ATTLIST apt:template
    xmlns:apt CDATA #FIXED "http://www.sun.com/jds/apoc/2004/template"
    xmlns:oor CDATA #FIXED "http://openoffice.org/2001/registry"
    xmlns:xs  CDATA #FIXED "http://www.w3.org/2001/XMLSchema"
    xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>

<!ELEMENT resImport EMPTY>
<!ATTLIST resImport
    apt:packagePath NMTOKEN #REQUIRED
>

<!ELEMENT category (category | page)>
<!ATTLIST category
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:inlineHelp NMTOKEN #IMPLIED
>

<!ELEMENT page ((section | set)+, xmlHandler*)>
<!ATTLIST page
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:inlineHelp NMTOKEN #IMPLIED
    apt:onlineHelp CDATA #IMPLIED
>

<!ELEMENT section (property+)>
<!ATTLIST section
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
>

<!ELEMENT set (page)>
<!ATTLIST set
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:labelPopup NMTOKEN #IMPLIED
    apt:dataPath CDATA #REQUIRED
    apt:elementNamePath CDATA #IMPLIED
>

<!ELEMENT property (constraints?, value*, visual?)>
<!ATTLIST property
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:inlineHelp NMTOKEN #IMPLIED
    apt:dataPath CDATA #REQUIRED
    oor:type (xs:boolean | xs:short | xs:int | xs:long | xs:double | xs:string | xs:hexBinary | oor:any | oor:boolean-list | oor:short-list | oor:int-list | oor:long-list | oor:double-list | oor:string-list | oor:hexBinary-list) #IMPLIED
    apt:storeDefault (true | false) #IMPLIED
    apt:xmlHandler IDREF #IMPLIED
>

<!ELEMENT visual (checkBox | chooser)?>
<!ATTLIST visual
    apt:type (textField | password | textArea | radioButtons | comboBox | stringList | colorSelector | hidden) #IMPLIED
>

<!ELEMENT  checkBox EMPTY>
<!ATTLIST checkBox
    apt:labelPost NMTOKEN #IMPLIED
>

<!ELEMENT  chooser EMPTY>
<!ATTLIST chooser
    apt:labelPopup NMTOKEN #IMPLIED
    apt:dataPath CDATA #IMPLIED
    apt:extendsChooser CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    xsi:nil (true | false) #IMPLIED
    oor:separator CDATA #IMPLIED
>

<!ELEMENT constraints (enumeration*, length?, minLength?, maxLength?, minInclusive?, maxInclusive?, minExclusive?, maxExclusive?)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
    oor:value CDATA #REQUIRED
    apt:label NMTOKEN #IMPLIED
>
<!ELEMENT length EMPTY>
<!ATTLIST length oor:value CDATA #REQUIRED
>
<!ELEMENT minLength EMPTY>
<!ATTLIST minLength oor:value CDATA #REQUIRED
>
<!ELEMENT maxLength EMPTY>
<!ATTLIST maxLength oor:value CDATA #REQUIRED
>
<!ELEMENT minInclusive EMPTY>
<!ATTLIST minInclusive oor:value CDATA #REQUIRED
>
<!ELEMENT maxInclusive EMPTY>
<!ATTLIST maxInclusive oor:value CDATA #REQUIRED
>
<!ELEMENT minExclusive EMPTY>
<!ATTLIST minExclusive oor:value CDATA #REQUIRED
>
<!ELEMENT maxExclusive EMPTY>
<!ATTLIST maxExclusive oor:value CDATA #REQUIRED
>

<!ELEMENT xmlHandler (event+, action+)>
<!ATTLIST xmlHandler apt:name ID #REQUIRED>

<!ELEMENT event EMPTY>
<!ATTLIST event apt:type (onChange) #IMPLIED>

<!ELEMENT action (choose|command)+>

<!ELEMENT choose (when+, otherwise?)>

<!ELEMENT when (command+)>
<!ATTLIST when apt:test CDATA #REQUIRED>

<!ELEMENT otherwise (command+)>

<!ELEMENT command (#PCDATA)>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/StarOffice8_pkg/templates/StarOffice8/Spreadsheet/ssGeneral.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either
 the GNU General Public License Version 2 only ("GPL") or
 the Common Development and Distribution License("CDDL")
 (collectively, the "License"). You may not use this file
 except in compliance with the License. You can obtain a copy
 of the License at www.sun.com/CDDL or at COPYRIGHT. See the
 License for the specific language governing permissions and
 limitations under the License. When distributing the software,
 include this License Header Notice in each file and include
 the License file at /legal/license.txt. If applicable, add the
 following below the License Header, with the fields enclosed
 by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by
 only the CDDL or only the GPL Version 2, indicate your
 decision by adding "[Contributor] elects to include this
 software in this distribution under the [CDDL or GPL
 Version 2] license." If you don't indicate a single choice
 of license, a recipient has the option to distribute your
 version of this file under either the CDDL, the GPL Version
 2 or to extend the choice of license to its licensees as
 provided above. However, if you add GPL Version 2 code and
 therefore, elected the GPL Version 2 license, then the
 option applies only if the new code is made subject to such
 option by the copyright holder.
-->
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
	<resImport apt:packagePath="com.sun.star8.apoc.policies.resource.staroffice_policies" />
	<category apt:name="StarOffice8" apt:label="SO.so8" apt:inlineHelp="SO.cat_staroffice_help">
		<category apt:name="Spreadsheet" apt:label="SO.spreadsheet" apt:inlineHelp="SO.spreadsheet_help">
			<page apt:name="General" apt:label="SO.ss.general" apt:inlineHelp="SO.ss.general_help" apt:onlineHelp="/StarOffice8/Spreadsheet/ssGeneral">
				<section apt:name="Update" apt:label="SO.ss.update">
					<property apt:dataPath="org.openoffice.Office.Calc/Content/Update/Link" apt:name="UpdateLinks" apt:label="SO.ss.up_links" oor:type="xs:int">
						<constraints>
							<enumeration oor:value="0" />
							<enumeration oor:value="2" />
							<enumeration oor:value="1" />
						</constraints>
						<value>2</value>
						<visual apt:type="radioButtons" />
					</property>
				</section>
				<section apt:name="Input" apt:label="SO.ss.input">
					<property apt:dataPath="org.openoffice.Office.Calc/Input/MoveSelection" apt:name="MoveSelection" apt:label="SO.ss.in_enter_on" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/MoveSelectionDirection" apt:name="MoveLocation" apt:label="SO.ss.in_enter_loc" oor:type="xs:int">
						<constraints>
							<enumeration oor:value="0" />
							<enumeration oor:value="1" />
							<enumeration oor:value="2" />
							<enumeration oor:value="3" />
						</constraints>
						<value>0</value>
						<visual apt:type="comboBox" />
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/SwitchToEditMode" apt:name="SwitchToEditMode" apt:label="SO.ss.in_enter_edit" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/ExpandFormatting" apt:name="ExpandFormatting" apt:label="SO.ss.in_format" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/ExpandReference" apt:name="ExpandReferences" apt:label="SO.ss.in_refs" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/HighlightSelection" apt:name="HighlightSelection" apt:label="SO.ss.in_highlight" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/UsePrinterMetrics" apt:name="UsePrinterMetrics" apt:label="SO.ss.in_printer" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Calc/Input/ReplaceCellsWarning" apt:name="OverwriteWarning" apt:label="SO.ss.in_paste" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
			</page>
		</category>
	</category>
</apt:template>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/Gnome2.6_pkg/templates/Gnome2.6/Display/windows.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either
 the GNU General Public License Version 2 only ("GPL") or
 the Common Development and Distribution License("CDDL")
 (collectively, the "License"). You may not use this file
 except in compliance with the License. You can obtain a copy
 of the License at www.sun.com/CDDL or at COPYRIGHT. See the
 License for the specific language governing permissions and
 limitations under the License. When distributing the software,
 include this License Header Notice in each file and include
 the License file at /legal/license.txt. If applicable, add the
 following below the License Header, with the fields enclosed
 by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by
 only the CDDL or only the GPL Version 2, indicate your
 decision by adding "[Contributor] elects to include this
 software in this distribution under the [CDDL or GPL
 Version 2] license." If you don't indicate a single choice
 of license, a recipient has the option to distribute your
 version of this file under either the CDDL, the GPL Version
 2 or to extend the choice of license to its licensees as
 provided above. However, if you add GPL Version 2 code and
 therefore, elected the GPL Version 2 license, then the
 option applies only if the new code is made subject to such
 option by the copyright holder.
-->
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
	<resImport apt:packagePath="org.gnome26.apoc.policies.resource.gnome_policies" />
	<category apt:name="Gnome2.6" apt:label="GNOME.gno2.6" apt:inlineHelp="GNOME.cat_gnome_help">
		<category apt:name="Display" apt:label="GNOME.display" apt:inlineHelp="GNOME.cat_display_help">
			<page apt:name="Windows" apt:label="GNOME.windows" apt:inlineHelp="GNOME.page_windows_help" apt:onlineHelp="/Gnome2.6/Display/windows">
				<section apt:name="FocusPrefs" apt:label="GNOME.focus_prefs">
					<property apt:dataPath="org.gnome.apps.metacity/general/focus_mode" apt:name="FocusMode" apt:label="GNOME.focus_mode" apt:xmlHandler="switchStateFocusMode" oor:type="xs:string" apt:inlineHelp="GNOME.focus_mode_help">
						<constraints>
							<enumeration oor:value="click" />
							<enumeration oor:value="mouse" />
							<enumeration oor:value="sloppy" />
						</constraints>
						<value>click</value>
						<visual apt:type="comboBox" />
					</property>
					<property apt:dataPath="org.gnome.apps.metacity/general/auto_raise" apt:name="AutoRaise" apt:label="GNOME.a_raise" apt:xmlHandler="switchStateAutoRaise" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.gnome.apps.metacity/general/auto_raise_delay" apt:name="AutoRaiseDelay" apt:label="GNOME.a_raise_delay" oor:type="xs:int">
						<value>500</value>
					</property>
					<property apt:dataPath="org.gnome.apps.metacity/general/button_layout" apt:name="ButtonLayout" apt:label="GNOME.btn_layout" oor:type="xs:string" apt:inlineHelp="GNOME.button_layout_help">
						<value>menu:minimize,maximize,close</value>
					</property>
					<property apt:dataPath="org.gnome.apps.metacity/general/action_double_click_titlebar" apt:name="DoubleClickBar" apt:label="GNOME.dble_click_tbar" oor:type="xs:string">
						<constraints>
							<enumeration oor:value="toggle_shade" />
							<enumeration oor:value="toggle_maximize" />
						</constraints>
						<value>toggle_maximize</value>
						<visual apt:type="radioButtons" />
					</property>
					<property apt:dataPath="org.gnome.apps.metacity/general/mouse_button_modifier" apt:name="MouseBtnMod" apt:label="GNOME.mouse_btn_mod" oor:type="xs:string" apt:inlineHelp="GNOME.mouse_button_modifier_help">
						<value>&lt;Alt&gt;</value>
					</property>
				</section>
				<section apt:name="WorkSpacePrefs" apt:label="GNOME.ws_prefs">
					<property apt:dataPath="org.gnome.apps.metacity/general/num_workspaces" apt:name="NumWorkspaces" apt:label="GNOME.no_of_ws" oor:type="xs:int">
						<value>4</value>
					</property>
					<property apt:dataPath="org.gnome.apps.metacity/workspace_names/name_1" apt:name="NameWorkspace1" apt:label="GNOME.ws_name1" oor:type="xs:string" />
					<property apt:dataPath="org.gnome.apps.metacity/workspace_names/name_2" apt:name="NameWorkspace2" apt:label="GNOME.ws_name2" oor:type="xs:string" />
					<property apt:dataPath="org.gnome.apps.metacity/workspace_names/name_3" apt:name="NameWorkspace3" apt:label="GNOME.ws_name3" oor:type="xs:string" />
					<property apt:dataPath="org.gnome.apps.metacity/workspace_names/name_4" apt:name="NameWorkspace4" apt:label="GNOME.ws_name4" oor:type="xs:string" />
					<property apt:dataPath="org.gnome.apps.metacity/workspace_names/name_5" apt:name="NameWorkspace5" apt:label="GNOME.ws_name5" oor:type="xs:string" />
					<property apt:dataPath="org.gnome.apps.metacity/workspace_names/name_6" apt:name="NameWorkspace6" apt:label="GNOME.ws_name6" oor:type="xs:string" />
				</section>
				<xmlHandler apt:name="switchStateFocusMode">
					<event apt:type="onChange" />
					<action>
						<choose>
							<when apt:test="((FocusMode.value=sloppy) or (FocusMode.value=mouse))">
								<command>AutoRaise.enabled=true</command>
							</when>
							<when apt:test="((FocusMode.value=sloppy) or (FocusMode.value=mouse) and (AutoRaise.value=true))">
								<command>AutoRaiseDelay.enabled=true</command>
							</when>
							<otherwise>
								<command>AutoRaise.enabled=false</command>
								<command>AutoRaiseDelay.enabled=false</command>
							</otherwise>
      						</choose>
					</action>
				</xmlHandler>
				<xmlHandler apt:name="switchStateAutoRaise">
					<event apt:type="onChange" />
					<action>
						<choose>
							<when apt:test="AutoRaise.value=true">
								<command>AutoRaiseDelay.enabled=true</command>
							</when>
							<otherwise>
								<command>AutoRaiseDelay.enabled=false</command>
							</otherwise>
						</choose>
					</action>
				</xmlHandler>
			</page>
		</category>
	</category>
</apt:template>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/StarOffice8_pkg/templates/StarOffice8/TextDocument/textFonts.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either
 the GNU General Public License Version 2 only ("GPL") or
 the Common Development and Distribution License("CDDL")
 (collectively, the "License"). You may not use this file
 except in compliance with the License. You can obtain a copy
 of the License at www.sun.com/CDDL or at COPYRIGHT. See the
 License for the specific language governing permissions and
 limitations under the License. When distributing the software,
 include this License Header Notice in each file and include
 the License file at /legal/license.txt. If applicable, add the
 following below the License Header, with the fields enclosed
 by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by
 only the CDDL or only the GPL Version 2, indicate your
 decision by adding "[Contributor] elects to include this
 software in this distribution under the [CDDL or GPL
 Version 2] license." If you don't indicate a single choice
 of license, a recipient has the option to distribute your
 version of this file under either the CDDL, the GPL Version
 2 or to extend the choice of license to its licensees as
 provided above. However, if you add GPL Version 2 code and
 therefore, elected the GPL Version 2 license, then the
 option applies only if the new code is made subject to such
 option by the copyright holder.
-->
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
	<resImport apt:packagePath="com.sun.star8.apoc.policies.resource.staroffice_policies" />
	<category apt:name="StarOffice8" apt:label="SO.so8" apt:inlineHelp="SO.cat_staroffice_help">
		<category apt:name="TextDocument" apt:label="SO.textDocument" apt:inlineHelp="SO.textDocument_help">
			<page apt:name="Fonts" apt:label="SO.text.fonts" apt:inlineHelp="SO.text.fonts_help" apt:onlineHelp="/StarOffice8/TextDocument/textFonts">
				<section apt:name="BasicFonts" apt:label="SO.text.fonts_basic">
					<property apt:dataPath="org.openoffice.Office.Writer/DefaultFont/Standard" apt:name="Default" apt:label="SO.text.fonts_def" oor:type="xs:string" apt:inlineHelp="SO.text.fonts_def_help">
						<constraints>
							<enumeration oor:value="Albany" />
							<enumeration oor:value="Andale Sans" />
							<enumeration oor:value="Andale Sans UI" />
							<enumeration oor:value="Arial Black" />
							<enumeration oor:value="Arial Narrow" />
							<enumeration oor:value="Avant Garde Gothic" />
							<enumeration oor:value="Baekmuk Batang" />
							<enumeration oor:value="Baekmuk Dotum" />
							<enumeration oor:value="Baekmuk Gulim" />
							<enumeration oor:value="Baekmuk Headline" />
							<enumeration oor:value="Bitstream Charter" />
							<enumeration oor:value="Bitstream Vera Sans" />
							<enumeration oor:value="Bitstream Vera Sans Mono" />
							<enumeration oor:value="Bitstream Vera Serif" />
							<enumeration oor:value="Bookman" />
							<enumeration oor:value="Broadway" />
							<enumeration oor:value="Century Schoolbook L" />
							<enumeration oor:value="Charter" />
							<enumeration oor:value="Courier" />
							<enumeration oor:value="Cumberland" />
							<enumeration oor:value="Dingbats" />
							<enumeration oor:value="FreeMono" />
							<enumeration oor:value="FreeSans" />
							<enumeration oor:value="FreeSerif" />
							<enumeration oor:value="FZFangSongTi" />
							<enumeration oor:value="FZHeiTi" />
							<enumeration oor:value="FZKaiTi" />
							<enumeration oor:value="FZSongTi" />
							<enumeration oor:value="Garamond" />
							<enumeration oor:value="Goha Tibeb Zemen" />
							<enumeration oor:value="Helvetica" />
							<enumeration oor:value="Imprint MT Shadow" />
							<enumeration oor:value="Kidprint" />
							<enumeration oor:value="Lucidabright" />
							<enumeration oor:value="Lucidasans" />
							<enumeration oor:value="Lucidatypewriter" />
							<enumeration oor:value="Luxi Mono" />
							<enumeration oor:value="Luxi Sans" />
							<enumeration oor:value="Luxi Serif" />
							<enumeration oor:value="New Century Schoolbook" />
							<enumeration oor:value="Nimbus Mono L" />
							<enumeration oor:value="Nimbus Roman No9 L" />
							<enumeration oor:value="Nimbus Sans L" />
							<enumeration oor:value="OmegaSerif88591" />
							<enumeration oor:value="OmegaSerif88592" />
							<enumeration oor:value="OmegaSerif88593" />
							<enumeration oor:value="OmegaSerif88594" />
							<enumeration oor:value="OmegaSerif88595" />
							<enumeration oor:value="OmegaSerifVISCII" />
							<enumeration oor:value="Palace Script" />
							<enumeration oor:value="Palatino" />
							<enumeration oor:value="Sheffield" />
							<enumeration oor:value="Standard Symbols L" />
							<enumeration oor:value="StarSymbol" />
							<enumeration oor:value="Sundotum" />
							<enumeration oor:value="Sundotumche" />
							<enumeration oor:value="Symbol" />
							<enumeration oor:value="Thorndale" />
							<enumeration oor:value="Times" />
							<enumeration oor:value="URW Bookman L" />
							<enumeration oor:value="URW Chancery L" />
							<enumeration oor:value="URW Gothic L" />
							<enumeration oor:value="URW Palladio L" />
							<enumeration oor:value="Utopia" />
							<enumeration oor:value="Zapf Chancery" />
							<enumeration oor:value="Zapf Dingbats" />
						</constraints>
						<value>Thorndale</value>
						<visual>
							<chooser apt:labelPopup="APOC.font.chooser.title" apt:dataPath="com.sun.apoc.manager/StarOffice/Choosers/Fonts" />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/DefaultFont/Heading" apt:name="Headings" apt:label="SO.text.fonts_head" oor:type="xs:string" apt:inlineHelp="SO.text.fonts_head_help">
						<value>Albany</value>
						<visual>
							<chooser apt:extendsChooser="/StarOffice8/TextDocument/Fonts/BasicFonts/Default" />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/DefaultFont/List" apt:name="Lists" apt:label="SO.text.fonts_list" oor:type="xs:string" apt:inlineHelp="SO.text.fonts_list_help">
						<value>Thorndale</value>
						<visual>
							<chooser apt:extendsChooser="/StarOffice8/TextDocument/Fonts/BasicFonts/Default" />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/DefaultFont/Caption" apt:name="Captions" apt:label="SO.text.fonts_caption" oor:type="xs:string" apt:inlineHelp="SO.text.fonts_caption_help">
						<value>Thorndale</value>
						<visual>
							<chooser apt:extendsChooser="/StarOffice8/TextDocument/Fonts/BasicFonts/Default" />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/DefaultFont/Index" apt:name="Index" apt:label="SO.text.fonts_index" oor:type="xs:string" apt:inlineHelp="SO.text.fonts_index_help">
						<value>Thorndale</value>
						<visual>
							<chooser apt:extendsChooser="/StarOffice8/TextDocument/Fonts/BasicFonts/Default" />
						</visual>
					</property>
				</section>
			</page>
		</category>
	</category>
</apt:template>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/Firefox1.5_pkg/templates/Advanced/advUpdate.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
   <resImport apt:packagePath="org.mozilla.apoc.policies.resource.firefox15_policies" />
     <category apt:name="Firefox1.5" apt:label="Firefox.firefox1.5" apt:inlineHelp="Firefox.cat_firefox_help">
      <category apt:name="Advnaced" apt:label="Firefox.advanced" apt:inlineHelp="Firefox.cat_advanced_help">
        <page apt:name="Update" apt:label="Firefox.advanced.update" apt:inlineHelp="Firefox.advanced.page_update_help" apt:onlineHelp="/Firefox1.5/Advanced/advUpdate">
         <section apt:name="SoftwareUpdate" apt:label="Firefox.advanced.software_update">
            <property apt:dataPath="org.mozilla.app/update/enabled" apt:name="UpdateEnabled" apt:label="Firefox.advanced.update_enabled" oor:type="xs:boolean">
               <value>true</value>
               <visual apt:type="checkBox" />
            </property>
            <property apt:dataPath="org.mozilla.extensions/update/enabled" apt:name="ExtensionsUpdateEnabled" apt:label="Firefox.advanced.extensions_update_enabled" oor:type="xs:boolean">
               <value>true</value>
               <visual apt:type="checkBox" />
            </property>
            <property apt:dataPath="org.mozilla.browser/search/update" apt:name="SearchUpdate" apt:label="Firefox.advanced.search_update" oor:type="xs:boolean">
               <value>true</value>
               <visual apt:type="checkBox" />
            </property>
         </section>
         <section apt:name="AutoUpdate" apt:label="Firefox.advanced.auto_update">
            <property apt:dataPath="org.mozilla.app/update/auto" apt:name="UpdateAuto" apt:label="Firefox.advanced.update_auto" oor:type="xs:boolean">
               <constraints>
                  <enumeration oor:value="true" />
                  <enumeration oor:value="false" />
               </constraints>
               <value>false</value>
               <visual apt:type="radioButtons" />
            </property>
            <property apt:dataPath="org.mozilla.app/update/mode" apt:name="UpdateMode" apt:label="Firefox.advanced.update_mode" oor:type="xs:int">
               <constraints>
                  <enumeration oor:value="0" />
                  <enumeration oor:value="1" />
               </constraints>
               <value>1</value>
               <visual apt:type="radioButtons" />
            </property>
         </section>
      </page>
    </category>
   </category>
</apt:template>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/Firefox1.5_pkg/templates/Privacy/privCookies.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
   <resImport apt:packagePath="org.mozilla.apoc.policies.resource.firefox15_policies" />
     <category apt:name="Firefox1.5" apt:label="Firefox.firefox1.5" apt:inlineHelp="Firefox.cat_firefox_help">
      <category apt:name="Privacy" apt:label="Firefox.privacy" apt:inlineHelp="Firefox.cat_privacy_help">
        <page apt:name="Cookies" apt:label="Firefox.privacy.cookies" apt:inlineHelp="Firefox.privacy.page_cookies_help" apt:onlineHelp="/Firefox1.5/General/privCookies">
          <section apt:name="Cookies" apt:label="Firefox.privacy.cookies">
             <property apt:dataPath="org.mozilla.network/cookie/cookieBehavior" apt:name="CookieBehavior" apt:label="Firefox.privacy.enable_cookies" oor:type="xs:int">
                 <constraints>
                    <enumeration oor:value="2" />
                    <enumeration oor:value="1" />
                    <enumeration oor:value="0" />
                 </constraints>
                 <value>0</value>
                 <visual apt:type="radioButtons" />
             </property>
             <property apt:dataPath="org.mozilla.network/cookie/lifetimePolicy" apt:name="cookie_lifetime_policy" apt:label="Firefox.privacy.lifetime_policy" oor:type="xs:int">
                <constraints>
                   <enumeration oor:value="0" />
                   <enumeration oor:value="1" />
                   <enumeration oor:value="2" />
                </constraints>
                <value>2</value>
                <visual apt:type="radioButtons" />
             </property>
          </section>
     </page>
    </category>
   </category>
</apt:template>
