=== freedesktop-unofficial-mirror/apoc-template-packages/packages/dtd/policytemplate.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 ******************************************************************************* 
 * $RCSfile: policytemplate.dtd,v $
 *
 * Description: This file contains the APOC Template DTD.
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * Use of this product is subject to license terms.
 *
 *******************************************************************************
--> 

<!ELEMENT apt:template (resImport*, category)>
<!ATTLIST apt:template
    xmlns:apt CDATA #FIXED "http://www.sun.com/jds/apoc/2004/template"
    xmlns:oor CDATA #FIXED "http://openoffice.org/2001/registry"
    xmlns:xs  CDATA #FIXED "http://www.w3.org/2001/XMLSchema"
    xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>

<!ELEMENT resImport EMPTY>
<!ATTLIST resImport
    apt:packagePath NMTOKEN #REQUIRED
>

<!ELEMENT category (category | page)>
<!ATTLIST category
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:inlineHelp NMTOKEN #IMPLIED
>

<!ELEMENT page ((section | set)+, xmlHandler*)>
<!ATTLIST page
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:inlineHelp NMTOKEN #IMPLIED
    apt:onlineHelp CDATA #IMPLIED
>

<!ELEMENT section (property+)>
<!ATTLIST section
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
>

<!ELEMENT set (page)>
<!ATTLIST set
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:labelPopup NMTOKEN #IMPLIED
    apt:dataPath CDATA #REQUIRED
    apt:elementNamePath CDATA #IMPLIED
>

<!ELEMENT property (constraints?, value*, visual?)>
<!ATTLIST property
    apt:name ID #REQUIRED
    apt:scope (user | host | global) #IMPLIED
    apt:label NMTOKEN #IMPLIED
    apt:inlineHelp NMTOKEN #IMPLIED
    apt:dataPath CDATA #REQUIRED
    oor:type (xs:boolean | xs:short | xs:int | xs:long | xs:double | xs:string | xs:hexBinary | oor:any | oor:boolean-list | oor:short-list | oor:int-list | oor:long-list | oor:double-list | oor:string-list | oor:hexBinary-list) #IMPLIED
    apt:storeDefault (true | false) #IMPLIED
    apt:xmlHandler IDREF #IMPLIED
>

<!ELEMENT visual (checkBox | chooser)?>
<!ATTLIST visual
    apt:type (textField | password | textArea | radioButtons | comboBox | stringList | colorSelector | hidden) #IMPLIED
>

<!ELEMENT  checkBox EMPTY>
<!ATTLIST checkBox
    apt:labelPost NMTOKEN #IMPLIED
>

<!ELEMENT  chooser EMPTY>
<!ATTLIST chooser
    apt:labelPopup NMTOKEN #IMPLIED
    apt:dataPath CDATA #IMPLIED
    apt:extendsChooser CDATA #IMPLIED
>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    xsi:nil (true | false) #IMPLIED
    oor:separator CDATA #IMPLIED
>

<!ELEMENT constraints (enumeration*, length?, minLength?, maxLength?, minInclusive?, maxInclusive?, minExclusive?, maxExclusive?)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
    oor:value CDATA #REQUIRED
    apt:label NMTOKEN #IMPLIED
>
<!ELEMENT length EMPTY>
<!ATTLIST length oor:value CDATA #REQUIRED
>
<!ELEMENT minLength EMPTY>
<!ATTLIST minLength oor:value CDATA #REQUIRED
>
<!ELEMENT maxLength EMPTY>
<!ATTLIST maxLength oor:value CDATA #REQUIRED
>
<!ELEMENT minInclusive EMPTY>
<!ATTLIST minInclusive oor:value CDATA #REQUIRED
>
<!ELEMENT maxInclusive EMPTY>
<!ATTLIST maxInclusive oor:value CDATA #REQUIRED
>
<!ELEMENT minExclusive EMPTY>
<!ATTLIST minExclusive oor:value CDATA #REQUIRED
>
<!ELEMENT maxExclusive EMPTY>
<!ATTLIST maxExclusive oor:value CDATA #REQUIRED
>

<!ELEMENT xmlHandler (event+, action+)>
<!ATTLIST xmlHandler apt:name ID #REQUIRED>

<!ELEMENT event EMPTY>
<!ATTLIST event apt:type (onChange) #IMPLIED>

<!ELEMENT action (choose|command)+>

<!ELEMENT choose (when+, otherwise?)>

<!ELEMENT when (command+)>
<!ATTLIST when apt:test CDATA #REQUIRED>

<!ELEMENT otherwise (command+)>

<!ELEMENT command (#PCDATA)>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/StarOffice8_pkg/templates/StarOffice8/LanguageSettings/lsWritingAids.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either
 the GNU General Public License Version 2 only ("GPL") or
 the Common Development and Distribution License("CDDL")
 (collectively, the "License"). You may not use this file
 except in compliance with the License. You can obtain a copy
 of the License at www.sun.com/CDDL or at COPYRIGHT. See the
 License for the specific language governing permissions and
 limitations under the License. When distributing the software,
 include this License Header Notice in each file and include
 the License file at /legal/license.txt. If applicable, add the
 following below the License Header, with the fields enclosed
 by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by
 only the CDDL or only the GPL Version 2, indicate your
 decision by adding "[Contributor] elects to include this
 software in this distribution under the [CDDL or GPL
 Version 2] license." If you don't indicate a single choice
 of license, a recipient has the option to distribute your
 version of this file under either the CDDL, the GPL Version
 2 or to extend the choice of license to its licensees as
 provided above. However, if you add GPL Version 2 code and
 therefore, elected the GPL Version 2 license, then the
 option applies only if the new code is made subject to such
 option by the copyright holder.
-->
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
	<resImport apt:packagePath="com.sun.star8.apoc.policies.resource.staroffice_policies" />
	<category apt:name="StarOffice8" apt:label="SO.so8" apt:inlineHelp="SO.cat_staroffice_help">
		<category apt:name="LanguageSettings" apt:label="SO.lang_sett" apt:inlineHelp="SO.cat_lang_settings_help">
			<page apt:name="WritingAids" apt:label="SO.ls.page_writing_aids" apt:inlineHelp="SO.ls.page_writing_aids_help" apt:onlineHelp="/StarOffice8/LanguageSettings/lsWritingAids">
				<section apt:name="UserDefinedDictionaries" apt:label="SO.ls.sect_user_dics">
					<property apt:dataPath="org.openoffice.Office.Linguistic/General/DictionaryList/ActiveDictionaries" apt:name="ActiveDictionaries" apt:label="SO.ls.active_dics" oor:type="oor:string-list" apt:inlineHelp="SO.ls.active_dics_help">
						<value>standard.dic sun.dic soffice.dic IgnoreAllList</value>
					</property>
				</section>
				<section apt:name="Options" apt:label="SO.ls.sect_options">
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsSpellUpperCase" apt:name="CheckUppercase" apt:label="SO.ls.options_uppercase" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsSpellWithDigits" apt:name="CheckWordsWithNumbers" apt:label="SO.ls.options_nums" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsSpellCapitalization" apt:name="CheckCapitalization" apt:label="SO.ls.options_capitals" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsSpellSpecial" apt:name="CheckSpecialRegions" apt:label="SO.ls.options_regions" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsSpellInAllLocales" apt:name="CheckAllLanguages" apt:label="SO.ls.options_langs" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsSpellAuto" apt:name="AutoCheck" apt:label="SO.ls.options_autocheck" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/SpellChecking/IsHideMarkings" apt:name="DoNotMarkErrors" apt:label="SO.ls.options_errors" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/General/IsGermanPreReform" apt:name="GermanSpellingOld" apt:label="SO.ls.options_german" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/Hyphenation/MinWordLength" apt:name="MinCharsForHyphenation" apt:label="SO.ls.options_hyphen" oor:type="xs:short">
						<value>5</value>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/Hyphenation/MinLeading" apt:name="CharsBeforeLineBreak" apt:label="SO.ls.options_before" oor:type="xs:short">
						<value>2</value>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/Hyphenation/MinTrailing" apt:name="CharsAfterLineBreak" apt:label="SO.ls.options_after" oor:type="xs:short">
						<value>2</value>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/Hyphenation/IsHyphAuto" apt:name="HyphenateWithoutInquiry" apt:label="SO.ls.options_inquiry" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Linguistic/Hyphenation/IsHyphSpecial" apt:name="HyphenateSpecialRegions" apt:label="SO.ls.options_special" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
			</page>
		</category>
	</category>
</apt:template>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/StarOffice8_pkg/templates/StarOffice8/StarOffice/soView.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either
 the GNU General Public License Version 2 only ("GPL") or
 the Common Development and Distribution License("CDDL")
 (collectively, the "License"). You may not use this file
 except in compliance with the License. You can obtain a copy
 of the License at www.sun.com/CDDL or at COPYRIGHT. See the
 License for the specific language governing permissions and
 limitations under the License. When distributing the software,
 include this License Header Notice in each file and include
 the License file at /legal/license.txt. If applicable, add the
 following below the License Header, with the fields enclosed
 by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by
 only the CDDL or only the GPL Version 2, indicate your
 decision by adding "[Contributor] elects to include this
 software in this distribution under the [CDDL or GPL
 Version 2] license." If you don't indicate a single choice
 of license, a recipient has the option to distribute your
 version of this file under either the CDDL, the GPL Version
 2 or to extend the choice of license to its licensees as
 provided above. However, if you add GPL Version 2 code and
 therefore, elected the GPL Version 2 license, then the
 option applies only if the new code is made subject to such
 option by the copyright holder.
-->
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
	<resImport apt:packagePath="com.sun.star8.apoc.policies.resource.staroffice_policies" />
	<category apt:name="StarOffice8" apt:label="SO.so8" apt:inlineHelp="SO.cat_staroffice_help">
		<category apt:name="StarOffice" apt:label="SO.so" apt:inlineHelp="SO.so.cat_staroffice_help">
			<page apt:name="View" apt:label="SO.so.page_view" apt:inlineHelp="SO.so.page_view_help" apt:onlineHelp="/StarOffice8/StarOffice/soView">
				<section apt:name="Display" apt:label="SO.so.sect_display">
					<property apt:dataPath="org.openoffice.Office.Common/View/FontScaling" apt:name="Scale" apt:label="SO.so.display_scale" oor:type="xs:short">
						<value>100</value>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/Misc/SymbolSet" apt:name="IconSize" apt:label="SO.so.display_icon" oor:type="xs:short">
						<constraints>
							<enumeration oor:value="0" />
							<enumeration oor:value="1" />
						</constraints>
						<value>0</value>
						<visual apt:type="comboBox" />
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/Accessibility/IsSystemFont" apt:name="UseSysFontForUI" apt:label="SO.so.misc_sys_font" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/View/FontAntiAliasing/Enabled" apt:name="FontAntialiasing" apt:label="SO.so.display_antia" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/View/FontAntiAliasing/MinPixelHeight" apt:name="AntialiasingFrom" apt:label="SO.so.display_antia_at" oor:type="xs:short">
						<value>8</value>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/Font/View/ShowFontBoxWYSIWYG" apt:name="PreviewInFontsList" apt:label="SO.so.display_preview" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/View/Menu/DontHideDisabledEntry" apt:name="InactiveMenuItems" apt:label="SO.so.display_inactive" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/Font/View/History" apt:name="FontHistory" apt:label="SO.so.display_font" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/View/Menu/ShowIconsInMenues" apt:name="ShowIconsInMenus" apt:label="SO.so.display_show" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
				<section apt:name="Restore" apt:label="SO.so.sect_restore">
					<property apt:dataPath="org.openoffice.Office.Common/Save/Document/ViewInfo" apt:name="EditingView" apt:label="SO.so.restore_editing" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/Save/Document/DocumentWindows" apt:name="OpenWindows" apt:label="SO.so.restore_open" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
				<section apt:name="View3D" apt:label="SO.so.sect_3d">
					<property apt:dataPath="org.openoffice.Office.Common/_3D_Engine/OpenGL" apt:name="UseOpenGL" apt:label="SO.so.3d_openGL" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/_3D_Engine/OpenGL_Faster" apt:name="OptimizedOutput" apt:label="SO.so.3d_optimized" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/_3D_Engine/Dithering" apt:name="UseDithering" apt:label="SO.so.3d_dithering" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/_3D_Engine/ShowFull" apt:name="ObjectRefreshDuringInteraction" apt:label="SO.so.3d_refresh" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
				<section apt:name="Mouse" apt:label="SO.so.sect_mouse">
					<property apt:dataPath="org.openoffice.Office.Common/View/Dialog/MousePositioning" apt:name="MousePositioning" apt:label="SO.so.mouse_positioning" oor:type="xs:short">
						<constraints>
							<enumeration oor:value="0" />
							<enumeration oor:value="1" />
							<enumeration oor:value="2" />
						</constraints>
						<value>2</value>
						<visual apt:type="comboBox" />
					</property>
					<property apt:dataPath="org.openoffice.Office.Common/View/Dialog/MiddleMouseButton" apt:name="MiddleMouseButton" apt:label="SO.so.mouse_middle" oor:type="xs:short">
						<constraints>
							<enumeration oor:value="0" />
							<enumeration oor:value="1" />
							<enumeration oor:value="2" />
						</constraints>
						<value>2</value>
						<visual apt:type="comboBox" />
					</property>
				</section>
			</page>
		</category>
	</category>
</apt:template>

=== freedesktop-unofficial-mirror/apoc-template-packages/packages/StarOffice8_pkg/templates/StarOffice8/TextDocument/textView.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 
 Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 
 The contents of this file are subject to the terms of either
 the GNU General Public License Version 2 only ("GPL") or
 the Common Development and Distribution License("CDDL")
 (collectively, the "License"). You may not use this file
 except in compliance with the License. You can obtain a copy
 of the License at www.sun.com/CDDL or at COPYRIGHT. See the
 License for the specific language governing permissions and
 limitations under the License. When distributing the software,
 include this License Header Notice in each file and include
 the License file at /legal/license.txt. If applicable, add the
 following below the License Header, with the fields enclosed
 by brackets [] replaced by your own identifying information:
 "Portions Copyrighted [year] [name of copyright owner]"
 
 Contributor(s):
 
 If you wish your version of this file to be governed by
 only the CDDL or only the GPL Version 2, indicate your
 decision by adding "[Contributor] elects to include this
 software in this distribution under the [CDDL or GPL
 Version 2] license." If you don't indicate a single choice
 of license, a recipient has the option to distribute your
 version of this file under either the CDDL, the GPL Version
 2 or to extend the choice of license to its licensees as
 provided above. However, if you add GPL Version 2 code and
 therefore, elected the GPL Version 2 license, then the
 option applies only if the new code is made subject to such
 option by the copyright holder.
-->
<!DOCTYPE apt:template SYSTEM "policytemplate.dtd">
<apt:template>
	<resImport apt:packagePath="com.sun.star8.apoc.policies.resource.staroffice_policies" />
	<category apt:name="StarOffice8" apt:label="SO.so8" apt:inlineHelp="SO.cat_staroffice_help">
		<category apt:name="TextDocument" apt:label="SO.textDocument" apt:inlineHelp="SO.textDocument_help">
			<page apt:name="View" apt:label="SO.text.view" apt:inlineHelp="SO.text.view_help" apt:onlineHelp="/StarOffice8/TextDocument/textView">
				<section apt:name="GuidesSection" apt:label="SO.text.guides">
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Line/Guide" apt:name="Guides" apt:label="SO.text.view_guides" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Line/SimpleControlPoint" apt:name="SimpleHandles" apt:label="SO.text.view_simp" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Line/LargeControlPoint" apt:name="LargeHandles" apt:label="SO.text.view_large" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
				<section apt:name="Views" apt:label="SO.text.sc_views">
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/HorizontalScroll" apt:name="HorizontalScroll" apt:label="SO.text.view_horiz" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/VerticalScroll" apt:name="VerticalScroll" apt:label="SO.text.view_vert" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/ShowRulers" apt:name="Ruler" apt:label="SO.text.view_ruler" apt:xmlHandler="switchStateRuler" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/HorizontalRuler" apt:name="HorizontalRuler" apt:label="SO.text.view_horiz_ruler" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/HorizontalRulerUnit" apt:name="HorizRulerUnit" apt:label="SO.text.view_hor_unit" oor:type="xs:int">
						<constraints>
							<enumeration oor:value="1" />
							<enumeration oor:value="2" />
							<enumeration oor:value="8" />
							<enumeration oor:value="7" />
							<enumeration oor:value="6" />
						</constraints>
						<value>8</value>
						<visual apt:type="comboBox" />
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/VerticalRuler" apt:name="VerticalRuler" apt:label="SO.text.view_vert_ruler" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/VerticalRulerUnit" apt:name="VertRulerUnit" apt:label="SO.text.view_vert_unit" oor:type="xs:int">
						<constraints>
							<enumeration oor:value="1" />
							<enumeration oor:value="2" />
							<enumeration oor:value="8" />
							<enumeration oor:value="7" />
							<enumeration oor:value="6" />
						</constraints>
						<value>8</value>
						<visual apt:type="comboBox" />
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Layout/Window/SmoothScroll" apt:name="SmoothScroll" apt:label="SO.text.view_smooth" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
				<section apt:name="Display" apt:label="SO.text.display">
					<property apt:dataPath="org.openoffice.Office.Writer/Content/Display/GraphicObject" apt:name="Graph" apt:label="SO.text.view_graph" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Content/Display/Table" apt:name="Tables" apt:label="SO.text.view_tabs" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Content/Display/DrawingControl" apt:name="Drawing" apt:label="SO.text.view_draw" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Content/Display/FieldCode" apt:name="Fields" apt:label="SO.text.view_field" oor:type="xs:boolean">
						<value>false</value>
						<visual>
							<checkBox />
						</visual>
					</property>
					<property apt:dataPath="org.openoffice.Office.Writer/Content/Display/Note" apt:name="Notes" apt:label="SO.text.view_notes" oor:type="xs:boolean">
						<value>true</value>
						<visual>
							<checkBox />
						</visual>
					</property>
				</section>
				<xmlHandler apt:name="switchStateRuler">
					<event apt:type="onChange" />
					<action>
						<choose>
							<when apt:test="Ruler.value=true">
								<command>HorizontalRuler.enabled=true</command>
								<command>HorizRulerUnit.enabled=true</command>
								<command>VerticalRuler.enabled=true</command>
								<command>VertRulerUnit.enabled=true</command>
							</when>
							<otherwise>
								<command>HorizontalRuler.enabled=false</command>
								<command>HorizRulerUnit.enabled=false</command>
								<command>VerticalRuler.enabled=false</command>
								<command>VertRulerUnit.enabled=false</command>
							</otherwise>
						</choose>
					</action>
				</xmlHandler>
			</page>
		</category>
	</category>
</apt:template>
